In [22]:
from influxdb import DataFrameClient
from functools import reduce
import numpy as np
import pandas as pd
import numpy as np
import operator as op
import multiprocessing as mp

In [23]:
dfclient = DataFrameClient('scruffy.soe.ucsc.edu', 8086, 'root', 'root', 'blackswan_dev')

In [24]:
dfclient.ping()

'1.7.9'

In [25]:
df = dfclient.query("select * from npb_cpu_st where \"testname\" = \'SP\' ")

In [26]:
df['npb_cpu_st']

,avail_threads,class,compile_date,compiler,dvfs,exec_time,flags,inc,iterations,lib,...,rand,run_uuid,size,socket,socket_num,testname,timestamp,total_threads,verification,version
2020-01-01 10:34:13.376564992+00:00,1,W,01 Jan 2020,f77,yes,3.830,-O3,(none),400,(none),...,(none),e6271413-1d86-4422-94ed-a5dbd96cc846,"0 36x 36x 36\nName: size, dtype: object",0,0,SP,1577873671,1,SUCCESSFUL,3.3.1
2020-01-01 10:53:59.346437888+00:00,1,W,01 Jan 2020,f77,yes,3.799,-O3,(none),400,(none),...,(none),1c008dc2-00ff-4f6c-9714-0b84ae171551,"0 36x 36x 36\nName: size, dtype: object",0,0,SP,1577874860,1,SUCCESSFUL,3.3.1
2020-01-02 16:20:08.558125056+00:00,1,W,02 Jan 2020,f77,yes,3.813,-O3,(none),400,(none),...,(none),534484a7-faea-4723-8252-5ecb4a24db77,"0 36x 36x 36\nName: size, dtype: object",0,0,SP,1577980760,1,SUCCESSFUL,3.3.1
2020-01-02 16:41:03.453566976+00:00,1,W,02 Jan 2020,f77,yes,3.789,-O3,(none),400,(none),...,(none),259df1fb-def3-462b-8729-5bf20cb7a78c,"0 36x 36x 36\nName: size, dtype: object",0,0,SP,1577982014,1,SUCCESSFUL,3.3.1
2020-01-02 17:02:01.271817984+00:00,1,W,02 Jan 2020,f77,yes,3.824,-O3,(none),400,(none),...,(none),3d60add7-ee24-48e9-be5b-059623e31dac,"0 36x 36x 36\nName: size, dtype: object",0,0,SP,1577983271,1,SUCCESSFUL,3.3.1
2020-01-02 17:58:39.298334976+00:00,1,W,02 Jan 2020,f77,yes,3.804,-O3,(none),400,(none),...,(none),562f3d3f-ee4d-49a2-b7e4-0c771a6c7f6c,"0 36x 36x 36\nName: size, dtype: object",0,0,SP,1577986670,1,SUCCESSFUL,3.3.1
2020-01-02 18:21:32.554740992+00:00,1,W,02 Jan 2020,f77,yes,3.799,-O3,(none),400,(none),...,(none),bf7fff23-c05a-4196-bd3e-4db1a0fe00e3,"0 36x 36x 36\nName: size, dtype: object",0,0,SP,1577988041,1,SUCCESSFUL,3.3.1
2020-01-02 19:55:01.562030080+00:00,1,W,02 Jan 2020,f77,yes,3.797,-O3,(none),400,(none),...,(none),b688e409-49ee-414f-b9e7-efc1383da1bd,"0 36x 36x 36\nName: size, dtype: object",0,0,SP,1577993653,1,SUCCESSFUL,3.3.1
2020-01-03 02:54:27.047118080+00:00,1,W,03 Jan 2020,f77,yes,3.805,-O3,(none),400,(none),...,(none),6b8a248c-8e23-45ad-bdd3-9679d0013ac8,"0 36x 36x 36\nName: size, dtype: object",0,0,SP,1578018815,1,SUCCESSFUL,3.3.1
2020-01-03 03:42:33.335090944+00:00,1,W,03 Jan 2020,f77,yes,3.817,-O3,(none),400,(none),...,(none),c82c00fa-edf1-40cb-a228-255a7646aa55,"0 36x 36x 36\nName: size, dtype: object",0,0,SP,1578021702,1,SUCCESSFUL,3.3.1
2020-01-03 04:29:01.756957952+00:00,1,W,03 Jan 2020,f77,yes,3.803,-O3,(none),400,(none),...,(none),9f49ba07-fabc-4f7b-91e8-dd054c148a76,"0 36x 36x 36\nName: size, dtype: object",0,0,SP,1578024490,1,SUCCESSFUL,3.3.1
2020-01-04 09:39:58.104264960+00:00,1,W,04 Jan 2020,f77,yes,5.272,-O3,(none),400,(none),...,(none),a71b55c8-6864-43e6-9fa4-0ebb00a88eac,"0 36x 36x 36\nName: size, dtype: object",0,0,SP,1578129045,1,SUCCESSFUL,3.3.1
2020-01-04 09:39:58.628258048+00:00,1,W,04 Jan 2020,f77,no,5.246,-O3,(none),400,(none),...,(none),a71b55c8-6864-43e6-9fa4-0ebb00a88eac,"0 36x 36x 36\nName: size, dtype: object",0,0,SP,1578129045,1,SUCCESSFUL,3.3.1

In [27]:
def median_and_ci(s):
    n = len(s)
    if n >= 10:
        s_median = s.median()
        lo_rank = int(np.rint(n / 2.0 - 1.96 * np.sqrt(n) / 2.0))
        hi_rank = int(np.rint(1 + n / 2.0 + 1.96 * np.sqrt(n) / 2.0))
        s_sorted = sorted(s.tolist())
        lo_val = s_sorted[lo_rank]
        hi_val = s_sorted[hi_rank]
        return s_median, lo_val, hi_val, 0
    else:
        # Not enough data to construct CI
        return None, None, None, 1

In [28]:
# median_and_ci(df['npb_cpu_mt']['mops_total'])

In [29]:
def ncr(n, r):
    r = min(r, n-r)
    if r == 0: return 1
    numer = reduce(op.mul, range(n, n-r, -1))
    denom = reduce(op.mul, range(1, r+1))
    return numer//denom

In [30]:
def ci_reduction(data, sample_size_min=10, sample_size_max=None, max_rep_count=20):
    if not sample_size_max:
        sample_size_max = len(data)

    ci = []
    for sample_size in range(sample_size_min, sample_size_max + 1):

        rep_count = min(max_rep_count, ncr(sample_size_max, sample_size))
        for rep in range(rep_count):
            np.random.seed()
            selected_sample = data.sample(sample_size)
            med, ci_lb, ci_ub, errc = median_and_ci(selected_sample)

            if not errc:
                ci.append({"rep": rep,
                           "sample_size": sample_size,
                           "med": med,
                           "ci_lb": ci_lb,
                           "ci_ub": ci_ub})

    return pd.DataFrame(ci)



def ci_reduction_trial(input_tuple):
    (data, sample_size_min, sample_size_max, rep) = input_tuple

    # Use different seed for each repetition
    np.random.seed()

    res = []

    # Skip some samples sizes for large sets -- do not consider every sample size to accelerate processing
    if sample_size_max < 200:
        # Every value
        studied_range = range(sample_size_min, sample_size_max + 1)
    elif sample_size_max < 500:
        # Fewer after 200, every second
        studied_range = range(sample_size_min, 200) + range(200, sample_size_max + 1, 2)
    elif sample_size_max < 1000:
        # In addition to previous range, even fewer after 500, every 10
        studied_range = range(sample_size_min, 200) + range(200, 500, 2) + range(500, sample_size_max + 1, 10)
    elif sample_size_max < 2000:
        # In addition to previous range, even fewer after 1000, every 50
        studied_range = range(sample_size_min, 200) + range(200, 500, 2) + range(500, 1000, 10) + range(1000, sample_size_max + 1, 50)
    else:
        # In addition to previous range, even fewer after 1000, every 100
        studied_range = range(sample_size_min, 200) + range(200, 500, 2) + range(500, 1000, 10) + range(1000, 2000, 50) + range(2000, sample_size_max + 1, 100)

    for sample_size in studied_range:

        selected_sample = data.sample(sample_size)
        med, ci_lb, ci_ub, errc = median_and_ci(selected_sample)

        if not errc:
            res.append({"rep": rep,
                       "sample_size": sample_size,
                       "med": med,
                       "ci_lb": ci_lb,
                       "ci_ub": ci_ub})

    return pd.DataFrame(res)




def ci_reduction_parallel(data, sample_size_min=10, sample_size_max=None, max_rep_count=20):
    """ Parallel version of ci_reduction()"""

    if not sample_size_max:
        sample_size_max = len(data)

    if sample_size_max >= sample_size_min:

        tasks = [(data, sample_size_min, sample_size_max, idx) for idx in range(max_rep_count)]

        #p = mp.Pool(mp.cpu_count())
        # Save 2 cores for other tasks
        p_count = max(mp.cpu_count() - 2, 1)
        p = mp.Pool(p_count)
        tasks_output = p.map(ci_reduction_trial, tasks)
        # Important to terminate processes
        p.terminate()

        all_output = pd.concat(tasks_output)
    else:
        all_output = pd.DataFrame()

    return all_output

In [31]:
df_indiv = ci_reduction_parallel(df['npb_cpu_st']['mops_total'], max_rep_count=200)

In [32]:
df_indiv

    rep  sample_size       med     ci_lb     ci_ub
0     0           10  3721.655  3706.884  3741.356
1     0           11  3725.641  3706.884  3741.356
2     0           12  3721.655  3706.884  3733.500
3     0           13  3725.641  3706.884  3733.500
0     1           10  3725.998  3713.226  3741.356
..  ...          ...       ...       ...       ...
3   198           13  3725.641  3706.884  3733.500
0   199           10  3722.012  3706.884  3733.500
1   199           11  3726.355  3713.226  3741.356
2   199           12  3725.998  3713.226  3733.500
3   199           13  3725.641  3706.884  3733.500

[800 rows x 5 columns]

In [33]:
if len(df_indiv) > 0:
    df_avg = df_indiv.groupby(['sample_size']).mean()
    df_avg["desired_lb"] = df_avg.med - 0.09 * df_avg.med
    df_avg["desired_ub"] = df_avg.med + 0.09 * df_avg.med
    df_avg["stopping_ub"] = df_avg["ci_ub"] <= df_avg["desired_ub"]
    df_avg["stopping_lb"] = df_avg["ci_lb"] >= df_avg["desired_lb"]
    df_avg["stopping"] = df_avg["stopping_lb"] & df_avg["stopping_ub"]
    df_avg["sample_size"] = df_avg.index.values
else:
    df_avg = pd.DataFrame()

In [34]:
df_avg

,rep,med,ci_lb,ci_ub,desired_lb,desired_ub,stopping_ub,stopping_lb,stopping,sample_size
sample_size,,,,,,,,,,
10,99.5,3722.857448,3706.23066,3739.363280,3387.800277,4057.914618,True,True,True,10
11,99.5,3723.413620,3703.84116,3739.715205,3388.306394,4058.520846,True,True,True,11
12,99.5,3723.616195,3708.81831,3733.227165,3388.490737,4058.741653,True,True,True,12
13,99.5,3725.641000,3706.88400,3733.500000,3390.333310,4060.948690,True,True,True,13

In [37]:
# calculation of E(x)
ci_can_stop = df_avg[df_avg["stopping"] == True]
if len(ci_can_stop):
    stop_at_sample_size_idx = ci_can_stop.index.min()
    print(stop_at_sample_size_idx)
    stop_at_sample_size = df['npb_cpu_st']['mops_total'].get_value(stop_at_sample_size_idx, "sample_size")
else:
    stop_at_sample_size = None

10

/Users/jayjeetchakraborty/mac-venv/lib/python3.7/site-packages/ipykernel_launcher.py:6: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

In [38]:
float(df_avg[df_avg['sample_size'] == stop_at_sample_size_idx].get('rep'))

99.5